### ISSUE TITLE
[Meta] Improve mesoscope data handling

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#822]
This is a meta-issue comprising the following issues:

- [ ] https://github.com/int-brain-lab/iblalyx/issues/72
- [ ] https://github.com/int-brain-lab/ibllib/issues/819
- [ ] https://github.com/int-brain-lab/ibllib/issues/820
- [ ] https://github.com/int-brain-lab/ibllib/issues/821
- [ ] https://github.com/int-brain-lab/iblenv/issues/376
